name: Sincronizar Fork con Original

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sincronizar Todas las Ramas
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

          git remote add upstream https://github.com/DesarrolloUneti/SIS-UNETI.git
          git fetch upstream

          for branch in $(git for-each-ref --format='%(refname:short)' refs/remotes/upstream/ | grep -vE '^upstream/(HEAD|main)$' | sed 's|^upstream/||'); do
            echo "Sincronizando rama: $branch"
            git checkout -B "$branch" "upstream/$branch"
            git push origin "$branch" --force
          done

          # Sincroniza main al final (puedes ponerlo al principio si prefieres)
          git checkout main
          git reset --hard upstream/main
          git push origin main --force
          
          git push --tags origin --force
